### ISSUE TITLE
Yaml to proto ?

### ISSUE THREAD

**Issue by gedw99** [krzko/proto2yaml#91]
Is it possible to do yaml to proto also ?

then we still get schema evolution behaviours. So any client can cope with field additions etc

**Comment by krzko** [comment]
Interesting, There is no reason why it couldn't be done. but I think it detracts form the real use of `.proto` files.

proto files are designed to be a concise and precise representation of a service definition, whereas YAML is a more human-readable and flexible format that allows for more variability and interpretation. 

The original use case I had was to use the generated output as a terraform input format, but can see how some folks will want to do what you mentioned.

It wasnt on the radar to add, but happy to take any sensible PR 😄

**Comment by gedw99** [comment]
hey @krzko  

i know what you mean about it not making sense.  It's just that i can code gen off the yaml --> Proto and then code gen from the proto --> golang.

I will try to get to this and make a PR.

**Comment by krzko** [comment]
Stale
